<dl>
		<dt><a href="http://www.ytnjob.com/index.php?m=IndexJob&a=jobView&job_id=[field:id /]" target="_blank"><img src="[field:company_logo /]" width="298" height="120" alt="[field:company_name /]" /></a></dt>
		<dd class="name"><a href="http://www.ytnjob.com/index.php?m=IndexJob&a=jobView&job_id=[field:id /]" target="_blank">[field:company_name /]</a></dd>
		<dd class="jj">[field:job_title /]</dd>
		<dd class="baoming">
		<span><a href="http://www.ytnjob.com/index.php?m=IndexJob&a=jobView&job_id=[field:id /]" title="点击报名"><img src="/files/lanling/go.png" width="80" height="40" alt="去看看" /></a></span>已有<strong><script src="http://www.1jobs.cn/job/plus/dj.php?companyid=[field:id /]" type='text/javascript' language="javascript"></script></strong>人报名
			
			
			</dd>
	</dl>