<a target="_blank" href="[field:arcurl/]"> <img width="120" height="120" src="[field:picname/]"</a>
				</div>
				<div class="info left">
				<div class="d1">
					<h3><a href="/jingdianyulu/">语录</a></h3><span>- 给力推荐！</span>
				</div>
				<div class="d2">
                                <a href="/shangganyuju/">伤感语句</a>
                                <a href="/youmeiyuju/" class="b">爱情语录</a>
                                <a href="/beishangyuju/">悲伤语句</a>
                                <a href="/zheliyuju/">哲理语句</a>
                                <a href="/mingrenyulu/">名人语录</a></div>
				</div>		
				<div class="d3">
				· <a target="_blank" title="[field:title/]" href="[field:arcurl/]">[field:title/]</a>